name: Github actions with maven build and deploy
on:
  push:
    branches:
      - SP1
jobs:
  Do-the-travis-thing:
    runs-on: ubuntu-20.04 #or ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          DB_DATABASE: sem3examdb
          DB_USER: ${{ secrets.DBUSER }}
          DB_PASSWORD: ${{ secrets.DBPW }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup jdk 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt' # openjdk see the setup java action: https://github.com/actions/setup-java
      - name: Set up DEPLOYED env variable
        run: echo "DEPLOYED=true" >> $GITHUB_ENV
      - name: mysql
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '8.0'
          mysql database: sem3examdb
          mysql user: ${{ secrets.DBUSER }}
          mysql password: ${{ secrets.DBPW }}
      - name: Cache Maven packages # cache maven repos to save time on future builds
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Maven verify
        run: mvn test
      - name: Maven deploy
        run: mvn -Dremote.user=${{ secrets.REMOTE_USER }} -Dremote.password=${{ secrets.REMOTE_PW }} tomcat7:deploy